# Generated by Django 4.2.19 on 2025-12-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
