# Generated by Django 4.2.19 on 2025-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
