# Generated by Django 4.2.19 on 2025-12-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TeamMember',
                'verbose_name_plural': 'TeamMembers',
                'db_table': 'TeamMember',
                'ordering': ['-created_at'],
            },
        ),
    ]
