# Generated by Django 4.2.19 on 2025-12-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
