# Generated by Django 4.2.19 on 2025-12-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email_url',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
